framework:
    messenger:
        transports:
            default: "%env(MESSENGER_TRANSPORT_DSN)%"

        routing:
            App\Message\DeleteUser: default
            App\Message\NewSubmission: default
            App\Message\DeleteImage: default
