services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    _instanceof:
        Doctrine\Common\DataFixtures\FixtureInterface:
            tags: ['doctrine.fixture.orm']

    App\Form\Extension\CaptchaBypassExtension:
        $bypass: true

    App\Mailer\ResetPasswordMailer:
        arguments:
            $noReplyAddress: "%env(NO_REPLY_ADDRESS)%"
            $secret: "%env(APP_SECRET)%"
            $siteName: Postmill

    App\Tests\Fixtures\:
        resource: '../tests/Fixtures'
